import { Produktkapabilitet, DigitaltProdukt } from "./types";

export const PRODUKTKAPABILITETER: Produktkapabilitet[] = [

  // ── PREHOSPITAL ─────────────────────────────────────────────────────────────
  {
    id: "pk01",
    navn: "Triagering og prioritering prehospitalt",
    beskrivelse: "Evnen til raskt å vurdere og prioritere pasienters alvorlighetsgrad utenfor sykehus",
    verdistrøm: "Prehospital",
    domeneId: "kunde-tjenestestyring",
    kritikalitet: "Høy",
    modenhetNå: 0, modenhetMål: 0,
    notater: "",
    spRolle: "IkkeVurdert",
  },
  {
    id: "pk02",
    navn: "Prehospital journalføring og datadeling",
    beskrivelse: "Evnen til å dokumentere og dele klinisk informasjon fra ambulanse til mottak i sanntid",
    verdistrøm: "Prehospital",
    domeneId: "data-integrasjon",
    kritikalitet: "Høy",
    modenhetNå: 0, modenhetMål: 0,
    notater: "Direkte avhengig av kjernekapabilitet: Datadeling og integrasjonsarkitektur",
    spRolle: "IkkeVurdert",
  },
  {
    id: "pk03",
    navn: "Koordinering mellom AMK og ambulanse",
    beskrivelse: "Evnen til å koordinere ressurser og kommunikasjon mellom operasjonssentral og felt",
    verdistrøm: "Prehospital",
    domeneId: "kunde-tjenestestyring",
    kritikalitet: "Høy",
    modenhetNå: 0, modenhetMål: 0,
    notater: "",
    spRolle: "IkkeVurdert",
  },

  // ── POLIKLINISK BEHANDLING ───────────────────────────────────────────────────
  {
    id: "pk04",
    navn: "Timebestilling og pasientflytplanlegging",
    beskrivelse: "Evnen til å planlegge og styre pasientflyt gjennom polikliniske forløp effektivt",
    verdistrøm: "Poliklinisk behandling",
    domeneId: "kunde-tjenestestyring",
    kritikalitet: "Høy",
    modenhetNå: 0, modenhetMål: 0,
    notater: "",
    spRolle: "IkkeVurdert",
  },
  {
    id: "pk05",
    navn: "Klinisk beslutningsstøtte poliklinikk",
    beskrivelse: "Evnen til å gi klinikere evidensbasert beslutningsstøtte i den kliniske hverdagen",
    verdistrøm: "Poliklinisk behandling",
    domeneId: "data-integrasjon",
    kritikalitet: "Middels",
    modenhetNå: 0, modenhetMål: 0,
    notater: "",
    spRolle: "IkkeVurdert",
  },

  // ── INNLEGGELSE OG AKUTTMOTTAK ───────────────────────────────────────────────
  {
    id: "pk06",
    navn: "Akuttmottak triagering og flytkoordinering",
    beskrivelse: "Evnen til å triagere og koordinere pasienter gjennom akuttmottaket effektivt",
    verdistrøm: "Innleggelse og akuttmottak",
    domeneId: "kunde-tjenestestyring",
    kritikalitet: "Høy",
    modenhetNå: 0, modenhetMål: 0,
    notater: "",
    spRolle: "IkkeVurdert",
  },
  {
    id: "pk07",
    navn: "Sengeplassering og kapasitetsstyring",
    beskrivelse: "Evnen til å styre sengeplasser og kapasitet på tvers av avdelinger i sanntid",
    verdistrøm: "Innleggelse og akuttmottak",
    domeneId: "kunde-tjenestestyring",
    kritikalitet: "Høy",
    modenhetNå: 0, modenhetMål: 0,
    notater: "",
    spRolle: "IkkeVurdert",
  },

  // ── OPERASJON OG PROSEDYRE ───────────────────────────────────────────────────
  {
    id: "pk08",
    navn: "Operasjonsplanlegging og ressursstyring",
    beskrivelse: "Evnen til å planlegge og koordinere operasjoner, utstyr og personell",
    verdistrøm: "Operasjon og prosedyre",
    domeneId: "kunde-tjenestestyring",
    kritikalitet: "Høy",
    modenhetNå: 0, modenhetMål: 0,
    notater: "",
    spRolle: "IkkeVurdert",
  },
  {
    id: "pk09",
    navn: "Medisinsk-teknisk utstyrsstyring (MTU)",
    beskrivelse: "Evnen til å forvalte og integrere medisinsk-teknisk utstyr i kliniske prosesser",
    verdistrøm: "Operasjon og prosedyre",
    domeneId: "plattform-infrastruktur",
    kritikalitet: "Høy",
    modenhetNå: 0, modenhetMål: 0,
    notater: "",
    spRolle: "IkkeVurdert",
  },

  // ── UTSKRIVELSE OG OPPFØLGING ────────────────────────────────────────────────
  {
    id: "pk10",
    navn: "Utskrivelsesplanlegging og epikrise",
    beskrivelse: "Evnen til å planlegge utskrivelse og produsere og distribuere epikrise",
    verdistrøm: "Utskrivelse og oppfølging",
    domeneId: "kunde-tjenestestyring",
    kritikalitet: "Høy",
    modenhetNå: 0, modenhetMål: 0,
    notater: "",
    spRolle: "IkkeVurdert",
  },
  {
    id: "pk11",
    navn: "Pasientrapportering og egenoppfølging",
    beskrivelse: "Evnen til å gi pasienten tilgang til egne helsedata og støtte egenoppfølging",
    verdistrøm: "Utskrivelse og oppfølging",
    domeneId: "kunde-tjenestestyring",
    kritikalitet: "Middels",
    modenhetNå: 0, modenhetMål: 0,
    notater: "",
    spRolle: "IkkeVurdert",
  },

  // ── DIGITAL HJEMMEOPPFØLGING ─────────────────────────────────────────────────
  {
    id: "pk12",
    navn: "Fjernmonitorering av pasient hjemme",
    beskrivelse: "Evnen til å monitorere pasienters helsetilstand fra hjemmet via digitale løsninger",
    verdistrøm: "Digital hjemmeoppfølging",
    domeneId: "data-integrasjon",
    kritikalitet: "Høy",
    modenhetNå: 0, modenhetMål: 0,
    notater: "",
    spRolle: "IkkeVurdert",
  },
  {
    id: "pk13",
    navn: "Videokonsultasjon og digital dialog",
    beskrivelse: "Evnen til å gjennomføre kliniske konsultasjoner digitalt",
    verdistrøm: "Digital hjemmeoppfølging",
    domeneId: "kunde-tjenestestyring",
    kritikalitet: "Middels",
    modenhetNå: 0, modenhetMål: 0,
    notater: "",
    spRolle: "IkkeVurdert",
  },

  // ── SAMHANDLING ──────────────────────────────────────────────────────────────
  {
    id: "pk14",
    navn: "Informasjonsdeling på tvers av omsorgsnivåer",
    beskrivelse: "Evnen til å dele relevant pasientinformasjon mellom spesialist- og primærhelsetjeneste",
    verdistrøm: "Samhandling",
    domeneId: "data-integrasjon",
    kritikalitet: "Høy",
    modenhetNå: 0, modenhetMål: 0,
    notater: "Direkte avhengig av kjernekapabilitet: Datadeling og integrasjonsarkitektur",
    spRolle: "IkkeVurdert",
  },
  {
    id: "pk15",
    navn: "Koordinert behandlingsplan på tvers",
    beskrivelse: "Evnen til å etablere og følge opp felles behandlingsplaner på tvers av aktører",
    verdistrøm: "Samhandling",
    domeneId: "kunde-tjenestestyring",
    kritikalitet: "Høy",
    modenhetNå: 0, modenhetMål: 0,
    notater: "",
    spRolle: "IkkeVurdert",
  },

  // ── HR OG KOMPETANSESTYRING ──────────────────────────────────────────────────
  {
    id: "pk16",
    navn: "Kompetanse- og turnusplanlegging",
    beskrivelse: "Evnen til å planlegge bemanning og kompetanse effektivt på tvers av enheter",
    verdistrøm: "HR og kompetansestyring",
    domeneId: "kompetanse-organisasjon",
    kritikalitet: "Høy",
    modenhetNå: 0, modenhetMål: 0,
    notater: "",
    spRolle: "IkkeVurdert",
  },

  // ── ØKONOMI OG LOGISTIKK ─────────────────────────────────────────────────────
  {
    id: "pk17",
    navn: "Medisinsk forbruksvarestyring og logistikk",
    beskrivelse: "Evnen til å styre innkjøp, lager og distribusjon av medisinske forbruksvarer",
    verdistrøm: "Økonomi og logistikk",
    domeneId: "kunde-tjenestestyring",
    kritikalitet: "Middels",
    modenhetNå: 0, modenhetMål: 0,
    notater: "",
    spRolle: "IkkeVurdert",
  },

  // ── FORSKNING OG INNOVASJON ──────────────────────────────────────────────────
  {
    id: "pk18",
    navn: "Tilgang til helsedata for forskning",
    beskrivelse: "Evnen til å gi forskere sikker tilgang til relevante helsedata under etterlevelse av personvern",
    verdistrøm: "Forskning og innovasjon",
    domeneId: "data-integrasjon",
    kritikalitet: "Middels",
    modenhetNå: 0, modenhetMål: 0,
    notater: "",
    spRolle: "IkkeVurdert",
  },
];

export const DIGITALE_PRODUKTER: DigitaltProdukt[] = [
  {
    id: "dp01",
    navn: "Prehospital journalløsning",
    beskrivelse: "Løsning for dokumentasjon og datadeling fra ambulanse til mottak",
    produktområde: "Kliniske produkter",
    produktkapabilitetIder: ["pk01", "pk02", "pk03"],
    kjernekapabilitetIder: ["kap-016", "kap-017", "k40"],
    status: "I produksjon",
    notater: "",
  },
  {
    id: "dp02",
    navn: "Prosessplattform (Pega)",
    beskrivelse: "Plattform for digitalisering og automatisering av administrative prosesser",
    produktområde: "Administrative produkter",
    produktkapabilitetIder: ["pk16", "pk17"],
    kjernekapabilitetIder: ["kap-016", "kap-017"],
    status: "Under utvikling",
    notater: "Oppstart vanskelig pga. manglende API-er i fagapplikasjoner. Illustrerer gap i kjernekapabilitet Datadeling og integrasjonsarkitektur.",
  },
  {
    id: "dp03",
    navn: "Digital hjemmeoppfølging",
    beskrivelse: "Løsning for fjernmonitorering og videokonsultasjon for pasienter hjemme",
    produktområde: "Kliniske produkter",
    produktkapabilitetIder: ["pk12", "pk13"],
    kjernekapabilitetIder: ["kap-016", "k37"],
    status: "Under utvikling",
    notater: "",
  },
  {
    id: "dp04",
    navn: "Samhandlingsløsning (M365/Teams)",
    beskrivelse: "Digital samhandlingsplattform for kommunikasjon og samarbeid",
    produktområde: "Administrative produkter",
    produktkapabilitetIder: ["pk14", "pk15"],
    kjernekapabilitetIder: ["kap-016", "kap-017"],
    status: "I produksjon",
    notater: "",
  },
  {
    id: "dp05",
    navn: "Helseanalyseplattform",
    beskrivelse: "Plattform for analyse av helsedata til forskning og kvalitetsforbedring",
    produktområde: "Produkter for bruker og datadrevet utvikling",
    produktkapabilitetIder: ["pk18"],
    kjernekapabilitetIder: ["kap-019", "k40", "k41"],
    status: "Idé",
    notater: "",
  },
];
