import { Kapabilitet } from "./types";

let _n = 0;
const id = () => `kap-${String(++_n).padStart(3, "0")}`;

export const SEED_DATA: Kapabilitet[] = [
  // ── DOMENE 1: Leveransedyktighet ─────────────────────────────────────────
  {
    id: id(), navn: "Produktteam-evne og agil leveranse",
    beskrivelse: "Evne til å organisere og operere tverrfaglige produktteam som leverer kontinuerlig verdi",
    domeneId: "leveransedyktighet", verdistrøm: "Utvikle nye produkter",
    teamtype: "Produktområde", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "UtvikleNytt", notater: "Pågående transformasjon til produktmodell — TeamTopologies innføres gradvis",
    realisering: {
      it4itKomponent: "Agile Planning",
      verktøy: ["Jira", "Confluence"],
      prosessReferanse: "Produktledelse og realisering",
      kompetansekrav: ["Product Owner", "Scrum Master", "Agil leveranse"],
    },
  },
  {
    id: id(), navn: "CI/CD og DevSecOps",
    beskrivelse: "Evne til å automatisere bygging, testing og utrulling av programvare med innebygd sikkerhet",
    domeneId: "leveransedyktighet", verdistrøm: "Utvikle nye produkter",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "UtvikleNytt", notater: "GitHub Actions innført for nye produkter, men legacy-systemer kjører fortsatt manuelt",
    realisering: {
      it4itKomponent: "Build and Test",
      verktøy: ["GitHub Actions", "Azure DevOps", "SonarQube"],
      prosessReferanse: "Systemutvikling og teknisk realisering",
      kompetansekrav: ["DevOps-ingeniør", "Sikkerhetsutvikler"],
    },
  },
  {
    id: id(), navn: "Testautomatisering og kvalitetssikring",
    beskrivelse: "Evne til systematisk å automatisere test og sikre produktkvalitet gjennom hele leveransekjeden",
    domeneId: "leveransedyktighet", verdistrøm: "Utvikle nye produkter",
    teamtype: "Produktområde", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Middels",
    modenhetNå: 1, modenhetMål: 3, klassifisering: "Endre", notater: "Manuell testing dominerer. Mangler felles rammeverk og kapasitet",
    realisering: {
      it4itKomponent: "Build and Test",
      verktøy: ["Selenium", "Cypress", "k6"],
      prosessReferanse: "Systemutvikling og teknisk realisering",
      kompetansekrav: ["Testleder", "Testautomatisering"],
    },
  },
  {
    id: id(), navn: "Release- og pakkestyring",
    beskrivelse: "Evne til å orkestrere og koordinere releaser på tvers av systemer og team",
    domeneId: "leveransedyktighet", verdistrøm: "Produksjonssette produkter",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 3, modenhetMål: 4, klassifisering: "Behold", notater: "ServiceNow CAB fungerer godt. Ønsker tettere integrasjon med CI/CD",
    realisering: {
      it4itKomponent: "Release Composition",
      verktøy: ["ServiceNow (CAB)", "Azure DevOps"],
      prosessReferanse: "Endringsstyring og release",
      kompetansekrav: ["Release Manager"],
    },
  },
  {
    id: id(), navn: "Teknisk gjeldsstyring",
    beskrivelse: "Evne til å identifisere, prioritere og håndtere teknisk gjeld systematisk",
    domeneId: "leveransedyktighet", verdistrøm: "Utvikle nye produkter",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Middels",
    modenhetNå: 1, modenhetMål: 3, klassifisering: "Endre", notater: "Teknisk gjeld kartlegges ad-hoc, ikke systematisk forvaltet i porteføljeprosessen",
    realisering: {
      it4itKomponent: "Portfolio Demand",
      verktøy: ["Jira", "SonarQube"],
      prosessReferanse: "Arkitektur og teknisk styring",
      kompetansekrav: ["Arkitekt", "Tech Lead"],
    },
  },
  {
    id: id(), navn: "Krav- og behovsstyring",
    beskrivelse: "Evne til å fange, strukturere og forvalte krav og behov fra brukere og kunder",
    domeneId: "leveransedyktighet", verdistrøm: "Utforske produkter",
    teamtype: "Produktområde", prosesstype: "Kjerne", eierskap: "Produkt", kritikalitet: "Middels",
    modenhetNå: 2, modenhetMål: 3, klassifisering: "Behold", notater: "",
    realisering: {
      it4itKomponent: "Requirement Management",
      verktøy: ["Jira", "Confluence", "Miro"],
      prosessReferanse: "Behovsstyring og tjenestedesign",
      kompetansekrav: ["Business Analyst", "Product Owner"],
    },
  },
  {
    id: id(), navn: "Tjenestedesign og UX",
    beskrivelse: "Evne til å designe brukersentrerte tjenester basert på innsikt og eksperimentering",
    domeneId: "leveransedyktighet", verdistrøm: "Utforske produkter",
    teamtype: "Produktområde", prosesstype: "Kjerne", eierskap: "Produkt", kritikalitet: "Middels",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "UtvikleNytt", notater: "Figma brukes, men tjenestedesign som disiplin er ikke systematisk forankret",
    realisering: {
      it4itKomponent: "Service Design",
      verktøy: ["Figma", "Maze", "Hotjar"],
      prosessReferanse: "Behovsstyring og tjenestedesign",
      kompetansekrav: ["UX-designer", "Tjenestedesigner"],
    },
  },
  {
    id: id(), navn: "Gevinstrealisering",
    beskrivelse: "Evne til å planlegge, følge opp og realisere gevinster fra investeringer og endringer",
    domeneId: "leveransedyktighet", verdistrøm: "Produksjonssette produkter",
    teamtype: "Produktområde", prosesstype: "Kjerne", eierskap: "Produkt", kritikalitet: "Middels",
    modenhetNå: 1, modenhetMål: 3, klassifisering: "Endre", notater: "Gevinster defineres i prosjektfasen men følges sjelden opp systematisk i drift",
    realisering: {
      it4itKomponent: "Portfolio Demand",
      verktøy: ["Excel", "PowerPoint", "SharePoint"],
      prosessReferanse: "Prosjekt og programstyring",
      kompetansekrav: ["Prosjektleder", "Gevinstrealisering"],
    },
  },

  // ── DOMENE 2: Plattform og infrastruktur ─────────────────────────────────
  {
    id: id(), navn: "Infrastruktur- og skyplattformstyring",
    beskrivelse: "Evne til å bygge, konfigurere og drifte skybasert infrastruktur og plattformer",
    domeneId: "plattform-infrastruktur", verdistrøm: "Tilgjengeliggjøre produkter",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 3, modenhetMål: 4, klassifisering: "Behold", notater: "Azure er primær skyplattform. Landing zones definert og operert",
    realisering: {
      it4itKomponent: "Resource Provisioning",
      verktøy: ["Azure", "Terraform", "Ansible"],
      prosessReferanse: "Plattform og infrastrukturstyring",
      kompetansekrav: ["Skyarkitekt", "Infrastrukturingeniør"],
    },
  },
  {
    id: id(), navn: "Cloud governance og FinOps",
    beskrivelse: "Evne til å styre skybruk, kostnader og etterlevelse på tvers av skyplattformer",
    domeneId: "plattform-infrastruktur", verdistrøm: "Tilgjengeliggjøre produkter",
    teamtype: "Plattformteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "Endre", notater: "Kostnadsoversikt mangler. FinOps-praksisen er i oppstartfase",
    realisering: {
      it4itKomponent: "Utility Monitoring",
      verktøy: ["Azure Cost Management", "Apptio"],
      prosessReferanse: "Leverandørstyring og anskaffelse",
      kompetansekrav: ["Cloud Architect", "FinOps-analytiker"],
    },
  },
  {
    id: id(), navn: "Infrastructure as Code (IaC)",
    beskrivelse: "Evne til å definere og forvalte infrastruktur som kode med versjonskontroll og automatisering",
    domeneId: "plattform-infrastruktur", verdistrøm: "Tilgjengeliggjøre produkter",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "UtvikleNytt", notater: "Terraform brukes i nye prosjekter. Mye manuell konfigurasjon i eldre miljøer",
    realisering: {
      it4itKomponent: "Resource Provisioning",
      verktøy: ["Terraform", "Bicep", "GitHub"],
      prosessReferanse: "Plattform og infrastrukturstyring",
      kompetansekrav: ["Platform Engineer", "DevOps-ingeniør"],
    },
  },
  {
    id: id(), navn: "Nettverksstyring og segmentering",
    beskrivelse: "Evne til å designe, drifte og sikre nettverksarkitektur inkl. zero-trust og mikrosegmentering",
    domeneId: "plattform-infrastruktur", verdistrøm: "Tilgjengeliggjøre produkter",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 3, modenhetMål: 4, klassifisering: "Behold", notater: "God nettverkskontroll. Zero-trust implementeres gradvis",
    realisering: {
      it4itKomponent: "Resource Provisioning",
      verktøy: ["Azure Virtual Network", "Cisco"],
      prosessReferanse: "Plattform og infrastrukturstyring",
      kompetansekrav: ["Nettverksingeniør", "Sikkerhetsarkitekt"],
    },
  },
  {
    id: id(), navn: "Kapasitetsstyring og skalering",
    beskrivelse: "Evne til å forutse, planlegge og skalere kapasitet i takt med etterspørselen",
    domeneId: "plattform-infrastruktur", verdistrøm: "Tilgjengeliggjøre produkter",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Middels",
    modenhetNå: 3, modenhetMål: 4, klassifisering: "Behold", notater: "",
    realisering: {
      it4itKomponent: "Capacity and Availability",
      verktøy: ["Azure Monitor", "Dynatrace"],
      prosessReferanse: "Kapasitet og tilgjengelighet",
      kompetansekrav: ["Kapasitetsplanlegger"],
    },
  },
  {
    id: id(), navn: "Konfigurasjonsstyring og CMDB",
    beskrivelse: "Evne til å kartlegge, vedlikeholde og utnytte konfigurasjonsinformasjon om IT-eiendeler",
    domeneId: "plattform-infrastruktur", verdistrøm: "Produksjonssette produkter",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "Endre", notater: "CMDB i ServiceNow har store datakvalitetsproblemer. Automatisk oppdatering mangler",
    realisering: {
      it4itKomponent: "Configuration Management",
      verktøy: ["ServiceNow CMDB"],
      prosessReferanse: "Konfigurasjonsstyring",
      kompetansekrav: ["CMDB-administrator"],
    },
  },
  {
    id: id(), navn: "Overvåkning og ytelsesstyring",
    beskrivelse: "Evne til å overvåke, analysere og optimalisere ytelse og tilgjengelighet på tvers av plattformer",
    domeneId: "plattform-infrastruktur", verdistrøm: "Drifte produkter",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 3, modenhetMål: 4, klassifisering: "Behold", notater: "Dynatrace dekker kritiske tjenester. Ønsker bedre korrelasjon mellom logger og traces",
    realisering: {
      it4itKomponent: "Monitoring and Alerting",
      verktøy: ["Dynatrace", "Azure Monitor", "Grafana"],
      prosessReferanse: "Kapasitet og tilgjengelighet",
      kompetansekrav: ["Site Reliability Engineer", "Driftsingeniør"],
    },
  },

  // ── DOMENE 3: Data og integrasjon ─────────────────────────────────────────
  {
    id: id(), navn: "Datadeling og integrasjonsarkitektur",
    beskrivelse: "Evne til å designe og forvalte dataflyt og integrasjoner mellom systemer og aktører",
    domeneId: "data-integrasjon", verdistrøm: "Tverrgående",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "UtvikleNytt", notater: "HL7 FHIR-strategi vedtatt, men implementasjonsgrad er lav. Mange punkt-til-punkt-integrasjoner",
    realisering: {
      it4itKomponent: "Service Integration",
      verktøy: ["MuleSoft", "Azure Integration Services", "HL7 FHIR"],
      prosessReferanse: "Integrasjon og datadeling",
      kompetansekrav: ["Integrasjonsarkitekt", "FHIR-spesialist"],
    },
  },
  {
    id: id(), navn: "API-styring og forvaltning",
    beskrivelse: "Evne til å publisere, versjonere, sikre og forvalte API-er som produkter",
    domeneId: "data-integrasjon", verdistrøm: "Tverrgående",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "UtvikleNytt", notater: "Azure APIM er valgt plattform. Developer portal er under etablering",
    realisering: {
      it4itKomponent: "Service Integration",
      verktøy: ["Azure API Management", "Swagger/OpenAPI"],
      prosessReferanse: "Integrasjon og datadeling",
      kompetansekrav: ["API-designer", "Platform Engineer"],
    },
  },
  {
    id: id(), navn: "Informasjons- og dataforvaltning",
    beskrivelse: "Evne til å forvalte datakvalitet, datakatalog, masterdata og dataeierskap",
    domeneId: "data-integrasjon", verdistrøm: "Tverrgående",
    teamtype: "Plattformteam", prosesstype: "Støtte", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 1, modenhetMål: 3, klassifisering: "Endre", notater: "Ingen formell datakatalog. Dataeierskap er uklart. Purview er anskaffet men ikke tatt i bruk",
    realisering: {
      it4itKomponent: "Data Governance",
      verktøy: ["Microsoft Purview", "Collibra"],
      prosessReferanse: "Informasjonsforvaltning",
      kompetansekrav: ["Data Steward", "Data Architect"],
    },
  },
  {
    id: id(), navn: "Analysekapabilitet og datainnsikt",
    beskrivelse: "Evne til å analysere data og produsere innsikt som understøtter beslutninger",
    domeneId: "data-integrasjon", verdistrøm: "Tverrgående",
    teamtype: "Støtteteam", prosesstype: "Støtte", eierskap: "Kjerne", kritikalitet: "Middels",
    modenhetNå: 2, modenhetMål: 3, klassifisering: "Endre", notater: "Power BI brukes av enkeltteam. Felles datamodell og Fabric er under utredning",
    realisering: {
      it4itKomponent: "Analytics",
      verktøy: ["Power BI", "Azure Synapse", "Fabric"],
      prosessReferanse: "Rapportering og analyse",
      kompetansekrav: ["Data Analyst", "Power BI-utvikler"],
    },
  },

  // ── DOMENE 4: Kunde og tjenestestyring ────────────────────────────────────
  {
    id: id(), navn: "Tjenestekatalog og bestillingsflyt",
    beskrivelse: "Evne til å tilby en strukturert, søkbar og selvbetjent tjenestekatalog med automatisert bestilling",
    domeneId: "kunde-tjenestestyring", verdistrøm: "Bruke produkter",
    teamtype: "Produktområde", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 3, modenhetMål: 4, klassifisering: "Behold", notater: "ServiceNow Service Portal fungerer godt for standard bestillinger",
    realisering: {
      it4itKomponent: "Service Catalog",
      verktøy: ["ServiceNow Service Portal"],
      prosessReferanse: "Tjenestekatalog og bestillingshåndtering",
      kompetansekrav: ["Tjenestedesigner", "ServiceNow-utvikler"],
    },
  },
  {
    id: id(), navn: "Hendelses- og problemhåndtering",
    beskrivelse: "Evne til å raskt gjenopprette tjenester ved hendelser og eliminere gjentakende problemer",
    domeneId: "kunde-tjenestestyring", verdistrøm: "Drifte produkter",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 4, modenhetMål: 5, klassifisering: "Behold", notater: "Velfungerende hendelsesprosess. P1/P2 SLA overholdes konsekvent",
    realisering: {
      it4itKomponent: "Incident Management",
      verktøy: ["ServiceNow ITSM", "PagerDuty"],
      prosessReferanse: "Hendelseshåndtering og problemstyring",
      kompetansekrav: ["Incident Manager", "Problem Manager"],
    },
  },
  {
    id: id(), navn: "Avtale- og SLA-styring",
    beskrivelse: "Evne til å definere, følge opp og rapportere på tjenestenivåavtaler og leveranseforpliktelser",
    domeneId: "kunde-tjenestestyring", verdistrøm: "Bruke produkter",
    teamtype: "Støtteteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 3, modenhetMål: 4, klassifisering: "Behold", notater: "",
    realisering: {
      it4itKomponent: "Service Level Management",
      verktøy: ["ServiceNow", "Power BI"],
      prosessReferanse: "Tjenestenivåstyring og kontraktforvaltning",
      kompetansekrav: ["Service Level Manager"],
    },
  },
  {
    id: id(), navn: "Onboarding og brukeradopsjon",
    beskrivelse: "Evne til å introdusere brukere til nye tjenester og sikre reell adopsjon og gevinst",
    domeneId: "kunde-tjenestestyring", verdistrøm: "Bruke produkter",
    teamtype: "Produktområde", prosesstype: "Kjerne", eierskap: "Produkt", kritikalitet: "Middels",
    modenhetNå: 2, modenhetMål: 3, klassifisering: "Endre", notater: "Onboarding er produktspesifikk og lite systematisert på tvers",
    realisering: {
      it4itKomponent: "User Experience Management",
      verktøy: ["WalkMe", "SharePoint", "Teams"],
      prosessReferanse: "Endrings- og adopsjonsledelse",
      kompetansekrav: ["Change Manager", "Opplæringsleder"],
    },
  },
  {
    id: id(), navn: "Bruker- og kundesupport (servicedesk)",
    beskrivelse: "Evne til å yte effektiv og kvalitetssikret brukerstøtte som første kontaktpunkt",
    domeneId: "kunde-tjenestestyring", verdistrøm: "Drifte produkter",
    teamtype: "Produktområde", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Middels",
    modenhetNå: 4, modenhetMål: 4, klassifisering: "Behold", notater: "Servicedesken håndterer høyt volum med god kvalitet. FCR over 70%",
    realisering: {
      it4itKomponent: "Incident Management",
      verktøy: ["ServiceNow", "Teams"],
      prosessReferanse: "Hendelseshåndtering og problemstyring",
      kompetansekrav: ["Servicedesk-agent", "Brukerstøtte"],
    },
  },
  {
    id: id(), navn: "Standardiserte katalogtjenester",
    beskrivelse: "Evne til å levere forhåndsdefinerte, standardiserte tjenestepakker som effektiviserer bestilling",
    domeneId: "kunde-tjenestestyring", verdistrøm: "Bruke produkter",
    teamtype: "Produktområde", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Middels",
    modenhetNå: 3, modenhetMål: 4, klassifisering: "Behold", notater: "",
    realisering: {
      it4itKomponent: "Service Catalog",
      verktøy: ["ServiceNow"],
      prosessReferanse: "Tjenestekatalog og bestillingshåndtering",
      kompetansekrav: ["Tjenestearkitekt"],
    },
  },

  // ── DOMENE 5: Sikkerhet og risiko ─────────────────────────────────────────
  {
    id: id(), navn: "Identitets- og tilgangsstyring (IAM)",
    beskrivelse: "Evne til å styre identiteter, tilganger og rettigheter på tvers av systemer og brukere",
    domeneId: "sikkerhet-risiko", verdistrøm: "Tverrgående",
    teamtype: "Plattformteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 3, modenhetMål: 5, klassifisering: "Endre", notater: "Entra ID er kjernen. MFA innført bredt, men privilegert tilgang har svakheter",
    realisering: {
      it4itKomponent: "Access Control",
      verktøy: ["Azure AD / Entra ID", "CyberArk", "BeyondTrust"],
      prosessReferanse: "Identitets- og tilgangsstyring",
      kompetansekrav: ["IAM-arkitekt", "Sikkerhetsadministrator"],
    },
  },
  {
    id: id(), navn: "Sikkerhetsovervåkning og hendelsesrespons (SOC)",
    beskrivelse: "Evne til å detektere, analysere og respondere på sikkerhetshendelser i sanntid",
    domeneId: "sikkerhet-risiko", verdistrøm: "Drifte produkter",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "UtvikleNytt", notater: "Sentinel er implementert. SOC-funksjonen er under etablering med ekstern leverandør",
    realisering: {
      it4itKomponent: "Security Monitoring",
      verktøy: ["Microsoft Sentinel", "Defender XDR"],
      prosessReferanse: "Sikkerhetsstyring (ISMS)",
      kompetansekrav: ["SOC-analytiker", "Incident Responder"],
    },
  },
  {
    id: id(), navn: "Sikkerhetsstyring (ISMS)",
    beskrivelse: "Evne til å etablere og vedlikeholde et ledelsessystem for informasjonssikkerhet iht. ISO 27001",
    domeneId: "sikkerhet-risiko", verdistrøm: "Tverrgående",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 3, modenhetMål: 4, klassifisering: "Behold", notater: "ISO 27001-sertifisering oppnådd. Kontinuerlig forbedring pågår",
    realisering: {
      it4itKomponent: "Security and Risk Management",
      verktøy: ["Resolver", "SharePoint"],
      prosessReferanse: "Sikkerhetsstyring (ISMS)",
      kompetansekrav: ["CISO", "Informasjonssikkerhetsrådgiver"],
    },
  },
  {
    id: id(), navn: "Risikostyring og personvern (GDPR)",
    beskrivelse: "Evne til å identifisere, vurdere og håndtere risiko inkl. personvernkonsekvenser",
    domeneId: "sikkerhet-risiko", verdistrøm: "Tverrgående",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 3, modenhetMål: 4, klassifisering: "Behold", notater: "DPIA-prosessen er etablert. Mangler automatisering av risikovurderinger",
    realisering: {
      it4itKomponent: "Security and Risk Management",
      verktøy: ["OneTrust", "SharePoint"],
      prosessReferanse: "Risiko- og personvernstyring",
      kompetansekrav: ["DPO", "Risikorådgiver"],
    },
  },
  {
    id: id(), navn: "Sikkerhetsgodkjenning og MTU-etterlevelse",
    beskrivelse: "Evne til å vurdere og godkjenne løsninger iht. sikkerhets- og MTU-krav fra Helse Sør-Øst",
    domeneId: "sikkerhet-risiko", verdistrøm: "Produksjonssette produkter",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 3, modenhetMål: 4, klassifisering: "Behold", notater: "",
    realisering: {
      it4itKomponent: "Security and Risk Management",
      verktøy: ["Resolver", "SharePoint"],
      prosessReferanse: "Sikkerhetsstyring (ISMS)",
      kompetansekrav: ["Sikkerhetsarkitekt", "MTU-rådgiver"],
    },
  },
  {
    id: id(), navn: "Leverandørkjedesikkerhet",
    beskrivelse: "Evne til å vurdere og styre sikkerhetsrisiko i leverandørkjeden (supply chain security)",
    domeneId: "sikkerhet-risiko", verdistrøm: "Drifte produkter",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 1, modenhetMål: 3, klassifisering: "Endre", notater: "NIS2 skjerper kravene. Leverandørvurdering er ikke systematisert",
    realisering: {
      it4itKomponent: "Security and Risk Management",
      verktøy: ["BitSight", "OneTrust"],
      prosessReferanse: "Leverandørstyring og anskaffelse",
      kompetansekrav: ["Leverandørsikkerhetsrådgiver"],
    },
  },
  {
    id: id(), navn: "Beredskap og kontinuitetsstyring",
    beskrivelse: "Evne til å planlegge og håndtere alvorlige driftsforstyrrelser og sikre tjenestekontinuitet",
    domeneId: "sikkerhet-risiko", verdistrøm: "Tilgjengeliggjøre produkter",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "Endre", notater: "BCP-planer finnes men er ikke testet regelmessig. Failover-øvelser mangler",
    realisering: {
      it4itKomponent: "Availability Management",
      verktøy: ["SharePoint", "Azure Site Recovery"],
      prosessReferanse: "Beredskap og kontinuitetsstyring",
      kompetansekrav: ["Beredskapskoordinator", "Business Continuity Manager"],
    },
  },

  // ── DOMENE 6: Styring og portefølje ───────────────────────────────────────
  {
    id: id(), navn: "Portefølje- og strategistyring",
    beskrivelse: "Evne til å forvalte og prioritere porteføljen av produkter og initiativer i tråd med strategi",
    domeneId: "styring-portefolje", verdistrøm: "Evaluere produkter",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "Endre", notater: "Porteføljestyring er under modenning. Mangler helhetlig prioriteringsmodell",
    realisering: {
      it4itKomponent: "Portfolio Demand",
      verktøy: ["ServiceNow PPM", "PowerBI"],
      prosessReferanse: "Porteføljestyring",
      kompetansekrav: ["Porteføljesjef", "Strategirådgiver"],
    },
  },
  {
    id: id(), navn: "Kapabilitetskartlegging og heatmap",
    beskrivelse: "Evne til å kartlegge, score og visualisere organisatoriske kapabiliteter og modenhet",
    domeneId: "styring-portefolje", verdistrøm: "Evaluere produkter",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 1, modenhetMål: 3, klassifisering: "UtvikleNytt", notater: "Denne applikasjonen er første steg. Workshop-basert kartlegging pågår",
    realisering: {
      it4itKomponent: "Portfolio Demand",
      verktøy: ["Denne applikasjonen", "Ardoq", "LeanIX"],
      prosessReferanse: "Virksomhetsarkitektur og metodestyring",
      kompetansekrav: ["Enterprise Architect", "Kapabilitetsanalytiker"],
    },
  },
  {
    id: id(), navn: "Investeringsstyring og business case",
    beskrivelse: "Evne til å strukturere og forankre investeringsbeslutninger med solide business cases",
    domeneId: "styring-portefolje", verdistrøm: "Evaluere produkter",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 3, klassifisering: "Behold", notater: "",
    realisering: {
      it4itKomponent: "Financial Management",
      verktøy: ["Excel", "PowerPoint"],
      prosessReferanse: "Finansiell styring og budsjett",
      kompetansekrav: ["Økonomianalytiker", "Prosjektleder"],
    },
  },
  {
    id: id(), navn: "Leverandørstyring og anskaffelse",
    beskrivelse: "Evne til å styre leverandørrelasjoner, kontrakter og anskaffelsesprosesser effektivt",
    domeneId: "styring-portefolje", verdistrøm: "Evaluere produkter",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 3, modenhetMål: 4, klassifisering: "Behold", notater: "Anskaffelsesprosessen er godt etablert. Leverandøroppfølging kan forbedres",
    realisering: {
      it4itKomponent: "Supplier Management",
      verktøy: ["Mercell", "SharePoint", "Visma"],
      prosessReferanse: "Leverandørstyring og anskaffelse",
      kompetansekrav: ["Innkjøpsleder", "Kontraktsforvalter"],
    },
  },
  {
    id: id(), navn: "Regulatorisk etterlevelse og rammestyring",
    beskrivelse: "Evne til å etterleve regulatoriske krav (NIS2, GDPR, Helsedatalov) og forvalte styringsrammer",
    domeneId: "styring-portefolje", verdistrøm: "Evaluere produkter",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 3, modenhetMål: 4, klassifisering: "Behold", notater: "NIS2 gjennomgang igangsatt. Helsedatalov-etterlevelse pågår",
    realisering: {
      it4itKomponent: "Governance and Compliance",
      verktøy: ["OneTrust", "SharePoint"],
      prosessReferanse: "Risiko- og personvernstyring",
      kompetansekrav: ["Compliance Officer", "Juridisk rådgiver"],
    },
  },
  {
    id: id(), navn: "Endringsstyring (Change Management)",
    beskrivelse: "Evne til å vurdere, koordinere og godkjenne endringer i IT-miljøet uten uønskede hendelser",
    domeneId: "styring-portefolje", verdistrøm: "Produksjonssette produkter",
    teamtype: "Støtteteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 3, modenhetMål: 4, klassifisering: "Behold", notater: "CAB-prosessen er velfungerende. Ønsker mer automatisk klassifisering av endringstyper",
    realisering: {
      it4itKomponent: "Change Control",
      verktøy: ["ServiceNow Change"],
      prosessReferanse: "Endringsstyring og release",
      kompetansekrav: ["Change Manager", "CAB-leder"],
    },
  },
  {
    id: id(), navn: "Virksomhetsarkitektur og metodestyring",
    beskrivelse: "Evne til å definere og forvalte virksomhetsarkitektur, prinsipper og tekniske standarder",
    domeneId: "styring-portefolje", verdistrøm: "Evaluere produkter",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "UtvikleNytt", notater: "EA-praksis er i støpeskjeen. Ardoq er anskaffet men lite brukt",
    realisering: {
      it4itKomponent: "Enterprise Architecture",
      verktøy: ["Ardoq", "Sparx EA", "LeanIX"],
      prosessReferanse: "Virksomhetsarkitektur og metodestyring",
      kompetansekrav: ["Enterprise Architect", "Løsningsarkitekt"],
    },
  },
  {
    id: id(), navn: "Kontinuerlig forbedring (CSIP)",
    beskrivelse: "Evne til å systematisk identifisere og realisere forbedringer i prosesser og tjenesteleveranse",
    domeneId: "styring-portefolje", verdistrøm: "Drifte produkter",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Middels",
    modenhetNå: 2, modenhetMål: 3, klassifisering: "Endre", notater: "CSIP-register finnes i ServiceNow men følges ikke opp strukturert",
    realisering: {
      it4itKomponent: "Continual Improvement",
      verktøy: ["ServiceNow", "Power BI"],
      prosessReferanse: "Kontinuerlig forbedring",
      kompetansekrav: ["Prosessrådgiver", "Kvalitetsleder"],
    },
  },

  // ── DOMENE 7: Kompetanse og organisasjon ─────────────────────────────────
  {
    id: id(), navn: "Kompetanseutvikling og talentstyring",
    beskrivelse: "Evne til å kartlegge, utvikle og beholde nødvendig kompetanse i organisasjonen",
    domeneId: "kompetanse-organisasjon", verdistrøm: "Tverrgående",
    teamtype: "Støtteteam", prosesstype: "Støtte", eierskap: "Kjerne", kritikalitet: "Middels",
    modenhetNå: 2, modenhetMål: 3, klassifisering: "Behold", notater: "",
    realisering: {
      it4itKomponent: "Human Resource Management",
      verktøy: ["SAP HCM", "LinkedIn Learning", "Cornerstone"],
      prosessReferanse: "Kompetanse- og ressursstyring",
      kompetansekrav: ["HR-Partner", "Learning & Development"],
    },
  },
  {
    id: id(), navn: "Ressursplanlegging og kapasitetsforvaltning",
    beskrivelse: "Evne til å planlegge og fordele menneskelige ressurser på tvers av team og prosjekter",
    domeneId: "kompetanse-organisasjon", verdistrøm: "Tverrgående",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Middels",
    modenhetNå: 2, modenhetMål: 3, klassifisering: "Behold", notater: "",
    realisering: {
      it4itKomponent: "Resource Management",
      verktøy: ["ServiceNow PPM", "Excel"],
      prosessReferanse: "Kompetanse- og ressursstyring",
      kompetansekrav: ["Ressursplanlegger", "PMO"],
    },
  },
  {
    id: id(), navn: "Organisasjonsdesign og teamprestasjon",
    beskrivelse: "Evne til å designe effektive organisasjonsstrukturer og utvikle høytytende team",
    domeneId: "kompetanse-organisasjon", verdistrøm: "Tverrgående",
    teamtype: "Støtteteam", prosesstype: "Støtte", eierskap: "Kjerne", kritikalitet: "Lav",
    modenhetNå: 2, modenhetMål: 3, klassifisering: "Endre", notater: "",
    realisering: {
      it4itKomponent: "Human Resource Management",
      verktøy: ["Miro", "PowerPoint"],
      prosessReferanse: "Kompetanse- og ressursstyring",
      kompetansekrav: ["Organisasjonsrådgiver", "Ledelseskonsulent"],
    },
  },
  {
    id: id(), navn: "Innovasjonsledelse og eksperimentering",
    beskrivelse: "Evne til å legge til rette for og styre innovasjonsinitiativ og strukturert eksperimentering",
    domeneId: "kompetanse-organisasjon", verdistrøm: "Utforske produkter",
    teamtype: "Støtteteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Lav",
    modenhetNå: 1, modenhetMål: 3, klassifisering: "UtvikleNytt", notater: "KI-CoE er etablert som innovasjonsnav. Bredere innovasjonskultur er under utvikling",
    realisering: {
      it4itKomponent: "Innovation Management",
      verktøy: ["Miro", "Teams", "Azure OpenAI"],
      prosessReferanse: "Behovsstyring og tjenestedesign",
      kompetansekrav: ["Innovasjonsrådgiver", "Design Thinking-fasilitator"],
    },
  },
  {
    id: id(), navn: "Kulturbygging og endringsevne",
    beskrivelse: "Evne til å bygge endringsvillig kultur og lede organisasjonen gjennom transformasjon",
    domeneId: "kompetanse-organisasjon", verdistrøm: "Tverrgående",
    teamtype: "Støtteteam", prosesstype: "Støtte", eierskap: "Kjerne", kritikalitet: "Middels",
    modenhetNå: 2, modenhetMål: 3, klassifisering: "Endre", notater: "",
    realisering: {
      it4itKomponent: "Human Resource Management",
      verktøy: ["Workplace Analytics", "Teams"],
      prosessReferanse: "Kompetanse- og ressursstyring",
      kompetansekrav: ["Change Manager", "Ledelsesrådgiver"],
    },
  },

  // ── TILGJENGELIGGJØRE PRODUKTER — Gartner ────────────────────────────────
  {
    id: "k35",
    navn: "Motstandsdyktighet, backup og katastrofegjenoppretting",
    beskrivelse: "Evnen til å sikre at kritiske tjenester kan gjenopprettes raskt etter uønskede hendelser",
    domeneId: "sikkerhet-risiko", verdistrøm: "Tilgjengeliggjøre produkter",
    teamtype: "Plattformteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "Endre", notater: "Azure Site Recovery er på plass. Mangler regelmessige failover-tester",
    realisering: {
      prosessreferanse: { prosesstype: "Styring", prosessnavn: "Forretningskontinuitet og beredskap" },
      it4itFunksjonellKomponent: { navn: "Availability Management", verdistrøm: "Operate" },
      verktøy: ["Azure Site Recovery", "Azure Backup"],
      gapÅrsak: "IkkeVurdert",
    },
    gartnerKategori: { domene: "Software, delivery and operations", kategori: "Resilience, backup, DR" },
  },
  {
    id: "k36",
    navn: "Container- og applikasjonsplattform",
    beskrivelse: "Evnen til å tilby og forvalte en standardisert plattform for containeriserte applikasjoner",
    domeneId: "plattform-infrastruktur", verdistrøm: "Tilgjengeliggjøre produkter",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "UtvikleNytt", notater: "AKS pilot er i gang. Behov for standardiserte helm charts og gitops-mønster",
    realisering: {
      prosessreferanse: { prosesstype: "Kjerne", prosessnavn: "Leveranse", underprosess: "Deploy" },
      it4itFunksjonellKomponent: { navn: "Deployment Management", verdistrøm: "Deploy" },
      verktøy: ["Azure Kubernetes Service (AKS)", "Docker"],
      gapÅrsak: "IkkeVurdert",
    },
    gartnerKategori: { domene: "Platforms", kategori: "Container platform" },
  },

  // ── DRIFTE PRODUKTER — Gartner ────────────────────────────────────────────
  {
    id: "k37",
    navn: "Observability og telemetri",
    beskrivelse: "Evnen til å forstå systemers indre tilstand gjennom logging, tracing og metrics på tvers av tjenester",
    domeneId: "plattform-infrastruktur", verdistrøm: "Drifte produkter",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "UtvikleNytt", notater: "OpenTelemetry standard vedtatt. Implementasjon pågår i nye tjenester",
    realisering: {
      prosessreferanse: { prosesstype: "Kjerne", prosessnavn: "Tjenesteproduksjon", underprosess: "Oppdage og rette" },
      it4itFunksjonellKomponent: { navn: "Monitoring and Event Management", verdistrøm: "Operate" },
      verktøy: ["Azure Monitor", "OpenTelemetry", "Grafana", "Splunk"],
      gapÅrsak: "IkkeVurdert",
    },
    gartnerKategori: { domene: "Software, delivery and operations", kategori: "Monitoring and observability" },
  },
  {
    id: "k38",
    navn: "Runtime applikasjonssikkerhet og API-sikkerhet",
    beskrivelse: "Evnen til å beskytte applikasjoner og API-er i produksjon mot angrep og misbruk",
    domeneId: "sikkerhet-risiko", verdistrøm: "Drifte produkter",
    teamtype: "Plattformteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 1, modenhetMål: 3, klassifisering: "Endre", notater: "WAF er på plass. RASP og API-sikkerhet er ikke systematisk implementert",
    realisering: {
      prosessreferanse: { prosesstype: "Styring", prosessnavn: "Sikkerhetsstyring", underprosess: "Applikasjonssikkerhet i drift" },
      it4itFunksjonellKomponent: { navn: "IT Security Management", verdistrøm: "Tverrgående" },
      verktøy: ["Azure API Management", "OWASP tools", "Defender for APIs"],
      gapÅrsak: "IkkeVurdert",
    },
    gartnerKategori: { domene: "Security, identity and access management", kategori: "Runtime application security", subkategori: "Runtime app and API security" },
  },

  // ── UTVIKLE NYE PRODUKTER — Gartner ──────────────────────────────────────
  {
    id: "k39",
    navn: "Apputviklingssikkerhet (DevSecOps)",
    beskrivelse: "Evnen til å integrere sikkerhet i hele utviklingsløpet — fra kode til produksjon",
    domeneId: "sikkerhet-risiko", verdistrøm: "Utvikle nye produkter",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "UtvikleNytt", notater: "GitHub Advanced Security aktivert. Secret scanning og SAST er operativt",
    realisering: {
      prosessreferanse: { prosesstype: "Kjerne", prosessnavn: "Leveranse", underprosess: "Test" },
      it4itFunksjonellKomponent: { navn: "Build Management", verdistrøm: "Integrate" },
      verktøy: ["GitHub Advanced Security", "SonarQube", "OWASP ZAP"],
      gapÅrsak: "IkkeVurdert",
    },
    gartnerKategori: { domene: "Software, delivery and operations", kategori: "App Dev security testing" },
  },

  // ── TVERRGÅENDE — Gartner ────────────────────────────────────────────────
  {
    id: "k40",
    navn: "Hendelsesdrevet datastrømming (event streaming)",
    beskrivelse: "Evnen til å prosessere og distribuere hendelser og data i sanntid på tvers av systemer",
    domeneId: "data-integrasjon", verdistrøm: "Tverrgående",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 1, modenhetMål: 3, klassifisering: "UtvikleNytt",
    notater: "Kritisk for sanntids kliniske data og integrasjon mellom fagapplikasjoner",
    realisering: {
      prosessreferanse: { prosesstype: "Styring", prosessnavn: "Styring av data og analysebehov", underprosess: "Sanntids datadeling" },
      it4itFunksjonellKomponent: { navn: "Integration Service", verdistrøm: "Integrate" },
      verktøy: ["Azure Event Hubs", "Apache Kafka", "Azure Service Bus"],
      gapÅrsak: "IkkeVurdert",
    },
    gartnerKategori: { domene: "Data and analytics services", kategori: "Event and streaming services" },
  },
  {
    id: "k41",
    navn: "KI og kognitive tjenester",
    beskrivelse: "Evnen til å ta i bruk og forvalte kunstig intelligens og maskinlæring i produkter og tjenester",
    domeneId: "data-integrasjon", verdistrøm: "Tverrgående",
    teamtype: "Støtteteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 1, modenhetMål: 3, klassifisering: "UtvikleNytt",
    notater: "Koblet til KI-CoE i Teknologi-avdelingen",
    realisering: {
      prosessreferanse: { prosesstype: "Kjerne", prosessnavn: "Produktledelse og produktutvikling", underprosess: "Tilrettelegge for innovasjon" },
      it4itFunksjonellKomponent: { navn: "Service Analytics & Intelligence", verdistrøm: "Tverrgående" },
      verktøy: ["Azure OpenAI", "Azure ML", "Microsoft Copilot"],
      gapÅrsak: "IkkeVurdert",
    },
    gartnerKategori: { domene: "Data and analytics services", kategori: "AI cognitive services" },
  },
  {
    id: "k42",
    navn: "Privilegert tilgangsstyring (PAM)",
    beskrivelse: "Evnen til å styre, overvåke og beskytte privilegerte tilganger til kritiske systemer",
    domeneId: "sikkerhet-risiko", verdistrøm: "Tverrgående",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "Endre", notater: "CyberArk er anskaffet men ikke fullstendig utrullet. Dekker kritiske servere",
    realisering: {
      prosessreferanse: { prosesstype: "Styring", prosessnavn: "Sikkerhetsstyring", underprosess: "Tilgangsstyring" },
      it4itFunksjonellKomponent: { navn: "IT Security Management", verdistrøm: "Tverrgående" },
      verktøy: ["CyberArk", "Azure PIM"],
      gapÅrsak: "IkkeVurdert",
    },
    gartnerKategori: { domene: "Security, identity and access management", kategori: "Privilege access management testing" },
  },
  {
    id: "k43",
    navn: "Trusseldeteksjon og hendelsesrespons (SIEM/SOAR)",
    beskrivelse: "Evnen til å detektere, analysere og respondere på sikkerhetstrusler systematisk",
    domeneId: "sikkerhet-risiko", verdistrøm: "Tverrgående",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "Endre", notater: "Sentinel er operativt med grunnleggende deteksjonsregler. SOAR-automatisering starter Q3",
    realisering: {
      prosessreferanse: { prosesstype: "Styring", prosessnavn: "Sikkerhetsstyring", underprosess: "Overvåkning og hendelsesrespons" },
      it4itFunksjonellKomponent: { navn: "IT Security Management", verdistrøm: "Tverrgående" },
      verktøy: ["Microsoft Sentinel", "Microsoft Defender XDR"],
      gapÅrsak: "IkkeVurdert",
    },
    gartnerKategori: { domene: "Security, identity and access management", kategori: "Threat detection, investigation and response" },
  },
];
