import { Kapabilitet } from "./types";

export const SEED_DATA: Kapabilitet[] = [
  // ── DOMENE 1: Leveransedyktighet ─────────────────────────────────────────
  {
    id: "kap-001", navn: "Produktteam-evne og agil leveranse",
    beskrivelse: "Evne til å organisere og operere tverrfaglige produktteam som leverer kontinuerlig verdi",
    domeneId: "leveransedyktighet", verdistrøm: "Utvikle nye produkter",
    teamtype: "Produktområde", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "UtvikleNytt", notater: "",
    realisering: {
      it4itKomponent: "Agile Planning",
      verktøy: ["Jira", "Confluence"],
      prosessReferanse: "Produktledelse og realisering",
      kompetansekrav: ["Product Owner", "Scrum Master", "Agil leveranse"],
    },
  },
  {
    id: "kap-002", navn: "CI/CD og DevSecOps",
    beskrivelse: "Evne til å automatisere bygging, testing og utrulling av programvare med innebygd sikkerhet",
    domeneId: "leveransedyktighet", verdistrøm: "Utvikle nye produkter",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "UtvikleNytt", notater: "",
    realisering: {
      it4itKomponent: "Build and Test",
      verktøy: ["GitHub Actions", "Azure DevOps", "SonarQube"],
      prosessReferanse: "Systemutvikling og teknisk realisering",
      kompetansekrav: ["DevOps-ingeniør", "Sikkerhetsutvikler"],
    },
  },
  {
    id: "kap-003", navn: "Testautomatisering og kvalitetssikring",
    beskrivelse: "Evne til systematisk å automatisere test og sikre produktkvalitet gjennom hele leveransekjeden",
    domeneId: "leveransedyktighet", verdistrøm: "Utvikle nye produkter",
    teamtype: "Produktområde", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 1, modenhetMål: 4, klassifisering: "Endre", notater: "",
    realisering: {
      it4itKomponent: "Build and Test",
      verktøy: ["Selenium", "Cypress", "k6"],
      prosessReferanse: "Systemutvikling og teknisk realisering",
      kompetansekrav: ["Testleder", "Testautomatisering"],
    },
  },
  {
    id: "kap-004", navn: "Release- og pakkestyring",
    beskrivelse: "Evne til å orkestrere og koordinere releaser på tvers av systemer og team",
    domeneId: "leveransedyktighet", verdistrøm: "Produksjonssette produkter",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 1, modenhetMål: 3, klassifisering: "UtvikleNytt", notater: "",
    realisering: {
      it4itKomponent: "Release Composition",
      verktøy: ["ServiceNow (CAB)", "Azure DevOps"],
      prosessReferanse: "Endringsstyring og release",
      kompetansekrav: ["Release Manager"],
    },
  },
  {
    id: "kap-005", navn: "Teknisk gjeldsstyring",
    beskrivelse: "Evne til å identifisere, prioritere og håndtere teknisk gjeld systematisk",
    domeneId: "leveransedyktighet", verdistrøm: "Utvikle nye produkter",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 1, modenhetMål: 3, klassifisering: "Endre", notater: "",
    realisering: {
      it4itKomponent: "Portfolio Demand",
      verktøy: ["Jira", "SonarQube"],
      prosessReferanse: "Arkitektur og teknisk styring",
      kompetansekrav: ["Arkitekt", "Tech Lead"],
    },
  },
  {
    id: "kap-006", navn: "Krav- og behovsstyring",
    beskrivelse: "Evne til å fange, strukturere og forvalte krav og behov fra brukere og kunder",
    domeneId: "leveransedyktighet", verdistrøm: "Utforske produkter",
    teamtype: "Produktområde", prosesstype: "Kjerne", eierskap: "Produkt", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "Endre", notater: "",
    realisering: {
      it4itKomponent: "Requirement Management",
      verktøy: ["Jira", "Confluence", "Miro"],
      prosessReferanse: "Behovsstyring og tjenestedesign",
      kompetansekrav: ["Business Analyst", "Product Owner"],
    },
  },
  {
    id: "kap-007", navn: "Tjenestedesign og UX",
    beskrivelse: "Evne til å designe brukersentrerte tjenester basert på innsikt og eksperimentering",
    domeneId: "leveransedyktighet", verdistrøm: "Utforske produkter",
    teamtype: "Produktområde", prosesstype: "Kjerne", eierskap: "Produkt", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "Endre", notater: "",
    realisering: {
      it4itKomponent: "Service Design",
      verktøy: ["Figma", "Maze", "Hotjar"],
      prosessReferanse: "Behovsstyring og tjenestedesign",
      kompetansekrav: ["UX-designer", "Tjenestedesigner"],
    },
  },
  {
    id: "kap-008", navn: "Gevinstrealisering",
    beskrivelse: "Evne til å planlegge, følge opp og realisere gevinster fra investeringer og endringer",
    domeneId: "leveransedyktighet", verdistrøm: "Produksjonssette produkter",
    teamtype: "Produktområde", prosesstype: "Kjerne", eierskap: "Produkt", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "Endre", notater: "",
    realisering: {
      it4itKomponent: "Portfolio Demand",
      verktøy: ["Excel", "PowerPoint", "SharePoint"],
      prosessReferanse: "Prosjekt og programstyring",
      kompetansekrav: ["Prosjektleder", "Gevinstrealisering"],
    },
  },

  // ── DOMENE 2: Plattform og infrastruktur ──────────────────────────────────
  {
    id: "kap-009", navn: "Infrastruktur- og skyplattformstyring",
    beskrivelse: "Evne til å bygge, konfigurere og drifte skybasert infrastruktur og plattformer",
    domeneId: "plattform-infrastruktur", verdistrøm: "Tilgjengeliggjøre produkter",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 3, modenhetMål: 5, klassifisering: "UtvikleNytt", notater: "",
    realisering: {
      it4itKomponent: "Resource Provisioning",
      verktøy: ["Azure", "Terraform", "Ansible"],
      prosessReferanse: "Plattform og infrastrukturstyring",
      kompetansekrav: ["Skyarkitekt", "Infrastrukturingeniør"],
    },
  },
  {
    id: "kap-010", navn: "Cloud governance og FinOps",
    beskrivelse: "Evne til å styre skybruk, kostnader og etterlevelse på tvers av skyplattformer",
    domeneId: "plattform-infrastruktur", verdistrøm: "Tilgjengeliggjøre produkter",
    teamtype: "Plattformteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Middels",
    modenhetNå: 3, modenhetMål: 4, klassifisering: "UtvikleNytt", notater: "",
    realisering: {
      it4itKomponent: "Utility Monitoring",
      verktøy: ["Azure Cost Management", "Apptio"],
      prosessReferanse: "Leverandørstyring og anskaffelse",
      kompetansekrav: ["Cloud Architect", "FinOps-analytiker"],
    },
  },
  {
    id: "kap-011", navn: "Infrastructure as Code (IaC)",
    beskrivelse: "Evne til å definere og forvalte infrastruktur som kode med versjonskontroll og automatisering",
    domeneId: "plattform-infrastruktur", verdistrøm: "Tilgjengeliggjøre produkter",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 3, modenhetMål: 4, klassifisering: "UtvikleNytt", notater: "",
    realisering: {
      it4itKomponent: "Resource Provisioning",
      verktøy: ["Terraform", "Bicep", "GitHub"],
      prosessReferanse: "Plattform og infrastrukturstyring",
      kompetansekrav: ["Platform Engineer", "DevOps-ingeniør"],
    },
  },
  {
    id: "kap-012", navn: "Nettverksstyring og segmentering",
    beskrivelse: "Evne til å designe, drifte og sikre nettverksarkitektur inkl. zero-trust og mikrosegmentering",
    domeneId: "plattform-infrastruktur", verdistrøm: "Tilgjengeliggjøre produkter",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "Endre", notater: "",
    realisering: {
      it4itKomponent: "Resource Provisioning",
      verktøy: ["Azure Virtual Network", "Cisco"],
      prosessReferanse: "Plattform og infrastrukturstyring",
      kompetansekrav: ["Nettverksingeniør", "Sikkerhetsarkitekt"],
    },
  },
  {
    id: "kap-013", navn: "Kapasitetsstyring og skalering",
    beskrivelse: "Evne til å forutse, planlegge og skalere kapasitet i takt med etterspørselen",
    domeneId: "plattform-infrastruktur", verdistrøm: "Tilgjengeliggjøre produkter",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Middels",
    modenhetNå: 1, modenhetMål: 3, klassifisering: "Behold", notater: "",
    realisering: {
      it4itKomponent: "Capacity and Availability",
      verktøy: ["Azure Monitor", "Dynatrace"],
      prosessReferanse: "Kapasitet og tilgjengelighet",
      kompetansekrav: ["Kapasitetsplanlegger"],
    },
  },
  {
    id: "kap-014", navn: "Konfigurasjonsstyring og CMDB",
    beskrivelse: "Evne til å kartlegge, vedlikeholde og utnytte konfigurasjonsinformasjon om IT-eiendeler",
    domeneId: "plattform-infrastruktur", verdistrøm: "Produksjonssette produkter",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 4, modenhetMål: 5, klassifisering: "Behold", notater: "",
    realisering: {
      it4itKomponent: "Configuration Management",
      verktøy: ["ServiceNow CMDB"],
      prosessReferanse: "Konfigurasjonsstyring",
      kompetansekrav: ["CMDB-administrator"],
    },
  },
  {
    id: "kap-015", navn: "Overvåkning og ytelsesstyring",
    beskrivelse: "Evne til å overvåke, analysere og optimalisere ytelse og tilgjengelighet på tvers av plattformer",
    domeneId: "plattform-infrastruktur", verdistrøm: "Drifte produkter",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Middels",
    modenhetNå: 4, modenhetMål: 5, klassifisering: "Behold", notater: "",
    realisering: {
      it4itKomponent: "Monitoring and Alerting",
      verktøy: ["Dynatrace", "Azure Monitor", "Grafana"],
      prosessReferanse: "Kapasitet og tilgjengelighet",
      kompetansekrav: ["Site Reliability Engineer", "Driftsingeniør"],
    },
  },

  // ── DOMENE 3: Data og integrasjon ─────────────────────────────────────────
  {
    id: "kap-016", navn: "Datadeling og integrasjonsarkitektur",
    beskrivelse: "Evne til å designe og forvalte dataflyt og integrasjoner mellom systemer og aktører",
    domeneId: "data-integrasjon", verdistrøm: "Tverrgående",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "Endre", notater: "",
    realisering: {
      it4itKomponent: "Service Integration",
      verktøy: ["MuleSoft", "Azure Integration Services", "HL7 FHIR"],
      prosessReferanse: "Integrasjon og datadeling",
      kompetansekrav: ["Integrasjonsarkitekt", "FHIR-spesialist"],
    },
  },
  {
    id: "kap-017", navn: "API-styring og forvaltning",
    beskrivelse: "Evne til å publisere, versjonere, sikre og forvalte API-er som produkter",
    domeneId: "data-integrasjon", verdistrøm: "Tverrgående",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 3, modenhetMål: 4, klassifisering: "Endre", notater: "",
    realisering: {
      it4itKomponent: "Service Integration",
      verktøy: ["Azure API Management", "Swagger/OpenAPI"],
      prosessReferanse: "Integrasjon og datadeling",
      kompetansekrav: ["API-designer", "Platform Engineer"],
    },
  },
  {
    id: "kap-018", navn: "Informasjons- og dataforvaltning",
    beskrivelse: "Evne til å forvalte datakvalitet, datakatalog, masterdata og dataeierskap",
    domeneId: "data-integrasjon", verdistrøm: "Tverrgående",
    teamtype: "Plattformteam", prosesstype: "Støtte", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "Endre", notater: "",
    realisering: {
      it4itKomponent: "Data Governance",
      verktøy: ["Microsoft Purview", "Collibra"],
      prosessReferanse: "Informasjonsforvaltning",
      kompetansekrav: ["Data Steward", "Data Architect"],
    },
  },
  {
    id: "kap-019", navn: "Analysekapabilitet og datainnsikt",
    beskrivelse: "Evne til å analysere data og produsere innsikt som understøtter beslutninger",
    domeneId: "data-integrasjon", verdistrøm: "Tverrgående",
    teamtype: "Støtteteam", prosesstype: "Støtte", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "UtvikleNytt", notater: "",
    realisering: {
      it4itKomponent: "Analytics",
      verktøy: ["Power BI", "Azure Synapse", "Fabric"],
      prosessReferanse: "Rapportering og analyse",
      kompetansekrav: ["Data Analyst", "Power BI-utvikler"],
    },
  },

  // ── DOMENE 4: Kunde- og tjenestestyring ───────────────────────────────────
  {
    id: "kap-020", navn: "Tjenestekatalog og bestillingsflyt",
    beskrivelse: "Evne til å tilby en strukturert, søkbar og selvbetjent tjenestekatalog med automatisert bestilling",
    domeneId: "kunde-tjenestestyring", verdistrøm: "Bruke produkter",
    teamtype: "Produktområde", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 5, klassifisering: "Behold", notater: "",
    realisering: {
      it4itKomponent: "Service Catalog",
      verktøy: ["ServiceNow Service Portal"],
      prosessReferanse: "Tjenestekatalog og bestillingshåndtering",
      kompetansekrav: ["Tjenestedesigner", "ServiceNow-utvikler"],
    },
  },
  {
    id: "kap-021", navn: "Hendelses- og problemhåndtering",
    beskrivelse: "Evne til å raskt gjenopprette tjenester ved hendelser og eliminere gjentakende problemer",
    domeneId: "kunde-tjenestestyring", verdistrøm: "Drifte produkter",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 4, modenhetMål: 5, klassifisering: "Behold", notater: "",
    realisering: {
      it4itKomponent: "Incident Management",
      verktøy: ["ServiceNow ITSM", "PagerDuty"],
      prosessReferanse: "Hendelseshåndtering og problemstyring",
      kompetansekrav: ["Incident Manager", "Problem Manager"],
    },
  },
  {
    id: "kap-022", navn: "Avtale- og SLA-styring",
    beskrivelse: "Evne til å definere, følge opp og rapportere på tjenestenivåavtaler og leveranseforpliktelser",
    domeneId: "kunde-tjenestestyring", verdistrøm: "Bruke produkter",
    teamtype: "Støtteteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Middels",
    modenhetNå: 4, modenhetMål: 5, klassifisering: "Behold", notater: "",
    realisering: {
      it4itKomponent: "Service Level Management",
      verktøy: ["ServiceNow", "Power BI"],
      prosessReferanse: "Tjenestenivåstyring og kontraktforvaltning",
      kompetansekrav: ["Service Level Manager"],
    },
  },
  {
    id: "kap-023", navn: "Onboarding og brukeradopsjon",
    beskrivelse: "Evne til å introdusere brukere til nye tjenester og sikre reell adopsjon og gevinst",
    domeneId: "kunde-tjenestestyring", verdistrøm: "Bruke produkter",
    teamtype: "Produktområde", prosesstype: "Kjerne", eierskap: "Produkt", kritikalitet: "Middels",
    modenhetNå: 1, modenhetMål: 3, klassifisering: "UtvikleNytt", notater: "",
    realisering: {
      it4itKomponent: "User Experience Management",
      verktøy: ["WalkMe", "SharePoint", "Teams"],
      prosessReferanse: "Endrings- og adopsjonsledelse",
      kompetansekrav: ["Change Manager", "Opplæringsleder"],
    },
  },
  {
    id: "kap-024", navn: "Bruker- og kundesupport (servicedesk)",
    beskrivelse: "Evne til å yte effektiv og kvalitetssikret brukerstøtte som første kontaktpunkt",
    domeneId: "kunde-tjenestestyring", verdistrøm: "Drifte produkter",
    teamtype: "Produktområde", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 4, modenhetMål: 5, klassifisering: "Behold", notater: "",
    realisering: {
      it4itKomponent: "Incident Management",
      verktøy: ["ServiceNow", "Teams"],
      prosessReferanse: "Hendelseshåndtering og problemstyring",
      kompetansekrav: ["Servicedesk-agent", "Brukerstøtte"],
    },
  },
  {
    id: "kap-025", navn: "Standardiserte katalogtjenester",
    beskrivelse: "Evne til å levere forhåndsdefinerte, standardiserte tjenestepakker som effektiviserer bestilling",
    domeneId: "kunde-tjenestestyring", verdistrøm: "Bruke produkter",
    teamtype: "Produktområde", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 1, modenhetMål: 4, klassifisering: "Behold", notater: "",
    realisering: {
      it4itKomponent: "Service Catalog",
      verktøy: ["ServiceNow"],
      prosessReferanse: "Tjenestekatalog og bestillingshåndtering",
      kompetansekrav: ["Tjenestearkitekt"],
    },
  },

  // ── DOMENE 5: Sikkerhet og risiko ─────────────────────────────────────────
  {
    id: "kap-026", navn: "Identitets- og tilgangsstyring (IAM)",
    beskrivelse: "Evne til å styre identiteter, tilganger og rettigheter på tvers av systemer og brukere",
    domeneId: "sikkerhet-risiko", verdistrøm: "Tverrgående",
    teamtype: "Plattformteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 3, modenhetMål: 4, klassifisering: "Behold", notater: "",
    realisering: {
      it4itKomponent: "Access Control",
      verktøy: ["Azure AD / Entra ID", "CyberArk", "BeyondTrust"],
      prosessReferanse: "Identitets- og tilgangsstyring",
      kompetansekrav: ["IAM-arkitekt", "Sikkerhetsadministrator"],
    },
  },
  {
    id: "kap-027", navn: "Sikkerhetsovervåkning og hendelsesrespons (SOC)",
    beskrivelse: "Evne til å detektere, analysere og respondere på sikkerhetshendelser i sanntid",
    domeneId: "sikkerhet-risiko", verdistrøm: "Drifte produkter",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 3, modenhetMål: 4, klassifisering: "Behold", notater: "",
    realisering: {
      it4itKomponent: "Security Monitoring",
      verktøy: ["Microsoft Sentinel", "Defender XDR"],
      prosessReferanse: "Sikkerhetsstyring (ISMS)",
      kompetansekrav: ["SOC-analytiker", "Incident Responder"],
    },
  },
  {
    id: "kap-028", navn: "Sikkerhetsstyring (ISMS)",
    beskrivelse: "Evne til å etablere og vedlikeholde et ledelsessystem for informasjonssikkerhet iht. ISO 27001",
    domeneId: "sikkerhet-risiko", verdistrøm: "Tverrgående",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 3, modenhetMål: 4, klassifisering: "Behold", notater: "",
    realisering: {
      it4itKomponent: "Security and Risk Management",
      verktøy: ["Resolver", "SharePoint"],
      prosessReferanse: "Sikkerhetsstyring (ISMS)",
      kompetansekrav: ["CISO", "Informasjonssikkerhetsrådgiver"],
    },
  },
  {
    id: "kap-029", navn: "Risikostyring og personvern (GDPR)",
    beskrivelse: "Evne til å identifisere, vurdere og håndtere risiko inkl. personvernkonsekvenser",
    domeneId: "sikkerhet-risiko", verdistrøm: "Tverrgående",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "Behold", notater: "",
    realisering: {
      it4itKomponent: "Security and Risk Management",
      verktøy: ["OneTrust", "SharePoint"],
      prosessReferanse: "Risiko- og personvernstyring",
      kompetansekrav: ["DPO", "Risikorådgiver"],
    },
  },
  {
    id: "kap-030", navn: "Sikkerhetsgodkjenning og MTU-etterlevelse",
    beskrivelse: "Evne til å vurdere og godkjenne løsninger iht. sikkerhets- og MTU-krav fra Helse Sør-Øst",
    domeneId: "sikkerhet-risiko", verdistrøm: "Produksjonssette produkter",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "Endre", notater: "",
    realisering: {
      it4itKomponent: "Security and Risk Management",
      verktøy: ["Resolver", "SharePoint"],
      prosessReferanse: "Sikkerhetsstyring (ISMS)",
      kompetansekrav: ["Sikkerhetsarkitekt", "MTU-rådgiver"],
    },
  },
  {
    id: "kap-031", navn: "Leverandørkjedesikkerhet",
    beskrivelse: "Evne til å vurdere og styre sikkerhetsrisiko i leverandørkjeden (supply chain security)",
    domeneId: "sikkerhet-risiko", verdistrøm: "Drifte produkter",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "Behold", notater: "",
    realisering: {
      it4itKomponent: "Security and Risk Management",
      verktøy: ["BitSight", "OneTrust"],
      prosessReferanse: "Leverandørstyring og anskaffelse",
      kompetansekrav: ["Leverandørsikkerhetsrådgiver"],
    },
  },
  {
    id: "kap-032", navn: "Beredskap og kontinuitetsstyring",
    beskrivelse: "Evne til å planlegge og håndtere alvorlige driftsforstyrrelser og sikre tjenestekontinuitet",
    domeneId: "sikkerhet-risiko", verdistrøm: "Tilgjengeliggjøre produkter",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "Endre", notater: "",
    realisering: {
      it4itKomponent: "Availability Management",
      verktøy: ["SharePoint", "Azure Site Recovery"],
      prosessReferanse: "Beredskap og kontinuitetsstyring",
      kompetansekrav: ["Beredskapskoordinator", "Business Continuity Manager"],
    },
  },

  // ── DOMENE 6: Styring og portefølje ──────────────────────────────────────
  {
    id: "kap-033", navn: "Portefølje- og strategistyring",
    beskrivelse: "Evne til å forvalte og prioritere porteføljen av produkter og initiativer i tråd med strategi",
    domeneId: "styring-portefolje", verdistrøm: "Evaluere produkter",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "Endre", notater: "",
    realisering: {
      it4itKomponent: "Portfolio Demand",
      verktøy: ["ServiceNow PPM", "PowerBI"],
      prosessReferanse: "Porteføljestyring",
      kompetansekrav: ["Porteføljesjef", "Strategirådgiver"],
    },
  },
  {
    id: "kap-034", navn: "Kapabilitetskartlegging og heatmap",
    beskrivelse: "Evne til å kartlegge, score og visualisere organisatoriske kapabiliteter og modenhet",
    domeneId: "styring-portefolje", verdistrøm: "Evaluere produkter",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 1, modenhetMål: 3, klassifisering: "Endre", notater: "",
    realisering: {
      it4itKomponent: "Portfolio Demand",
      verktøy: ["Denne applikasjonen", "Ardoq", "LeanIX"],
      prosessReferanse: "Virksomhetsarkitektur og metodestyring",
      kompetansekrav: ["Enterprise Architect", "Kapabilitetsanalytiker"],
    },
  },
  {
    id: "kap-035", navn: "Investeringsstyring og business case",
    beskrivelse: "Evne til å strukturere og forankre investeringsbeslutninger med solide business cases",
    domeneId: "styring-portefolje", verdistrøm: "Evaluere produkter",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "Endre", notater: "",
    realisering: {
      it4itKomponent: "Financial Management",
      verktøy: ["Excel", "PowerPoint"],
      prosessReferanse: "Finansiell styring og budsjett",
      kompetansekrav: ["Økonomianalytiker", "Prosjektleder"],
    },
  },
  {
    id: "kap-036", navn: "Leverandørstyring og anskaffelse",
    beskrivelse: "Evne til å styre leverandørrelasjoner, kontrakter og anskaffelsesprosesser effektivt",
    domeneId: "styring-portefolje", verdistrøm: "Evaluere produkter",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "Endre", notater: "",
    realisering: {
      it4itKomponent: "Supplier Management",
      verktøy: ["Mercell", "SharePoint", "Visma"],
      prosessReferanse: "Leverandørstyring og anskaffelse",
      kompetansekrav: ["Innkjøpsleder", "Kontraktsforvalter"],
    },
  },
  {
    id: "kap-037", navn: "Regulatorisk etterlevelse og rammestyring",
    beskrivelse: "Evne til å etterleve regulatoriske krav (NIS2, GDPR, Helsedatalov) og forvalte styringsrammer",
    domeneId: "styring-portefolje", verdistrøm: "Evaluere produkter",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 4, klassifisering: "Endre", notater: "",
    realisering: {
      it4itKomponent: "Governance and Compliance",
      verktøy: ["OneTrust", "SharePoint"],
      prosessReferanse: "Risiko- og personvernstyring",
      kompetansekrav: ["Compliance Officer", "Juridisk rådgiver"],
    },
  },
  {
    id: "kap-038", navn: "Endringsstyring (Change Management)",
    beskrivelse: "Evne til å vurdere, koordinere og godkjenne endringer i IT-miljøet uten uønskede hendelser",
    domeneId: "styring-portefolje", verdistrøm: "Produksjonssette produkter",
    teamtype: "Støtteteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 3, modenhetMål: 4, klassifisering: "Endre", notater: "",
    realisering: {
      it4itKomponent: "Change Control",
      verktøy: ["ServiceNow Change"],
      prosessReferanse: "Endringsstyring og release",
      kompetansekrav: ["Change Manager", "CAB-leder"],
    },
  },
  {
    id: "kap-039", navn: "Virksomhetsarkitektur og metodestyring",
    beskrivelse: "Evne til å definere og forvalte virksomhetsarkitektur, prinsipper og tekniske standarder",
    domeneId: "styring-portefolje", verdistrøm: "Evaluere produkter",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 1, modenhetMål: 3, klassifisering: "Endre", notater: "",
    realisering: {
      it4itKomponent: "Enterprise Architecture",
      verktøy: ["Ardoq", "Sparx EA", "LeanIX"],
      prosessReferanse: "Virksomhetsarkitektur og metodestyring",
      kompetansekrav: ["Enterprise Architect", "Løsningsarkitekt"],
    },
  },
  {
    id: "kap-040", navn: "Kontinuerlig forbedring (CSIP)",
    beskrivelse: "Evne til å systematisk identifisere og realisere forbedringer i prosesser og tjenesteleveranse",
    domeneId: "styring-portefolje", verdistrøm: "Drifte produkter",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 1, modenhetMål: 3, klassifisering: "UtvikleNytt", notater: "",
    realisering: {
      it4itKomponent: "Continual Improvement",
      verktøy: ["ServiceNow", "Power BI"],
      prosessReferanse: "Kontinuerlig forbedring",
      kompetansekrav: ["Prosessrådgiver", "Kvalitetsleder"],
    },
  },

  // ── DOMENE 7: Kompetanse og organisasjon ─────────────────────────────────
  {
    id: "kap-041", navn: "Kompetanseutvikling og talentstyring",
    beskrivelse: "Evne til å kartlegge, utvikle og beholde nødvendig kompetanse i organisasjonen",
    domeneId: "kompetanse-organisasjon", verdistrøm: "Tverrgående",
    teamtype: "Støtteteam", prosesstype: "Støtte", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 1, modenhetMål: 3, klassifisering: "UtvikleNytt", notater: "",
    realisering: {
      it4itKomponent: "Human Resource Management",
      verktøy: ["SAP HCM", "LinkedIn Learning", "Cornerstone"],
      prosessReferanse: "Kompetanse- og ressursstyring",
      kompetansekrav: ["HR-Partner", "Learning & Development"],
    },
  },
  {
    id: "kap-042", navn: "Ressursplanlegging og kapasitetsforvaltning",
    beskrivelse: "Evne til å planlegge og fordele menneskelige ressurser på tvers av team og prosjekter",
    domeneId: "kompetanse-organisasjon", verdistrøm: "Tverrgående",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 3, klassifisering: "UtvikleNytt", notater: "",
    realisering: {
      it4itKomponent: "Resource Management",
      verktøy: ["ServiceNow PPM", "Excel"],
      prosessReferanse: "Kompetanse- og ressursstyring",
      kompetansekrav: ["Ressursplanlegger", "PMO"],
    },
  },
  {
    id: "kap-043", navn: "Organisasjonsdesign og teamprestasjon",
    beskrivelse: "Evne til å designe effektive organisasjonsstrukturer og utvikle høytytende team",
    domeneId: "kompetanse-organisasjon", verdistrøm: "Tverrgående",
    teamtype: "Støtteteam", prosesstype: "Støtte", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 2, modenhetMål: 3, klassifisering: "Endre", notater: "",
    realisering: {
      it4itKomponent: "Human Resource Management",
      verktøy: ["Miro", "PowerPoint"],
      prosessReferanse: "Kompetanse- og ressursstyring",
      kompetansekrav: ["Organisasjonsrådgiver", "Ledelseskonsulent"],
    },
  },
  {
    id: "kap-044", navn: "Innovasjonsledelse og eksperimentering",
    beskrivelse: "Evne til å legge til rette for og styre innovasjonsinitiativ og strukturert eksperimentering",
    domeneId: "kompetanse-organisasjon", verdistrøm: "Utforske produkter",
    teamtype: "Støtteteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 1, modenhetMål: 3, klassifisering: "UtvikleNytt", notater: "",
    realisering: {
      it4itKomponent: "Innovation Management",
      verktøy: ["Miro", "Teams", "Azure OpenAI"],
      prosessReferanse: "Behovsstyring og tjenestedesign",
      kompetansekrav: ["Innovasjonsrådgiver", "Design Thinking-fasilitator"],
    },
  },
  {
    id: "kap-045", navn: "Kulturbygging og endringsevne",
    beskrivelse: "Evne til å bygge endringsvillig kultur og lede organisasjonen gjennom transformasjon",
    domeneId: "kompetanse-organisasjon", verdistrøm: "Tverrgående",
    teamtype: "Støtteteam", prosesstype: "Støtte", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 1, modenhetMål: 3, klassifisering: "UtvikleNytt", notater: "",
    realisering: {
      it4itKomponent: "Human Resource Management",
      verktøy: ["Workplace Analytics", "Teams"],
      prosessReferanse: "Kompetanse- og ressursstyring",
      kompetansekrav: ["Change Manager", "Ledelsesrådgiver"],
    },
  },

  // ── Gartner ETRA-kapabiliteter (ikke vurdert ennå) ───────────────────────
  {
    id: "k35", navn: "Motstandsdyktighet, backup og katastrofegjenoppretting",
    beskrivelse: "Evnen til å sikre at kritiske tjenester kan gjenopprettes raskt etter uønskede hendelser",
    domeneId: "sikkerhet-risiko", verdistrøm: "Tilgjengeliggjøre produkter",
    teamtype: "Plattformteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 0, modenhetMål: 0, klassifisering: "IkkeVurdert", notater: "",
    realisering: { verktøy: ["Azure Site Recovery", "Azure Backup"] },
    gartnerKategori: { domene: "Software, delivery and operations", kategori: "Resilience, backup, DR" },
  },
  {
    id: "k36", navn: "Container- og applikasjonsplattform",
    beskrivelse: "Evnen til å tilby og forvalte en standardisert plattform for containeriserte applikasjoner",
    domeneId: "plattform-infrastruktur", verdistrøm: "Tilgjengeliggjøre produkter",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 0, modenhetMål: 0, klassifisering: "IkkeVurdert", notater: "",
    realisering: { verktøy: ["Azure Kubernetes Service (AKS)", "Docker"] },
    gartnerKategori: { domene: "Platforms", kategori: "Container platform" },
  },
  {
    id: "k37", navn: "Observability og telemetri",
    beskrivelse: "Evnen til å forstå systemers indre tilstand gjennom logging, tracing og metrics på tvers av tjenester",
    domeneId: "plattform-infrastruktur", verdistrøm: "Drifte produkter",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 0, modenhetMål: 0, klassifisering: "IkkeVurdert", notater: "",
    realisering: { verktøy: ["Azure Monitor", "OpenTelemetry", "Grafana", "Splunk"] },
    gartnerKategori: { domene: "Software, delivery and operations", kategori: "Monitoring and observability" },
  },
  {
    id: "k38", navn: "Runtime applikasjonssikkerhet og API-sikkerhet",
    beskrivelse: "Evnen til å beskytte applikasjoner og API-er i produksjon mot angrep og misbruk",
    domeneId: "sikkerhet-risiko", verdistrøm: "Drifte produkter",
    teamtype: "Plattformteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 0, modenhetMål: 0, klassifisering: "IkkeVurdert", notater: "",
    realisering: { verktøy: ["Azure API Management", "OWASP tools", "Defender for APIs"] },
    gartnerKategori: { domene: "Security, identity and access management", kategori: "Runtime application security" },
  },
  {
    id: "k39", navn: "Apputviklingssikkerhet (DevSecOps)",
    beskrivelse: "Evnen til å integrere sikkerhet i hele utviklingsløpet — fra kode til produksjon",
    domeneId: "sikkerhet-risiko", verdistrøm: "Utvikle nye produkter",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 0, modenhetMål: 0, klassifisering: "IkkeVurdert", notater: "",
    realisering: { verktøy: ["GitHub Advanced Security", "SonarQube", "OWASP ZAP"] },
    gartnerKategori: { domene: "Software, delivery and operations", kategori: "App Dev security testing" },
  },
  {
    id: "k40", navn: "Hendelsesdrevet datastrømming (event streaming)",
    beskrivelse: "Evnen til å prosessere og distribuere hendelser og data i sanntid på tvers av systemer",
    domeneId: "data-integrasjon", verdistrøm: "Tverrgående",
    teamtype: "Plattformteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 0, modenhetMål: 0, klassifisering: "IkkeVurdert",
    notater: "Kritisk for sanntids kliniske data og integrasjon mellom fagapplikasjoner",
    realisering: { verktøy: ["Azure Event Hubs", "Apache Kafka", "Azure Service Bus"] },
    gartnerKategori: { domene: "Data and analytics services", kategori: "Event and streaming services" },
  },
  {
    id: "k41", navn: "KI og kognitive tjenester",
    beskrivelse: "Evnen til å ta i bruk og forvalte kunstig intelligens og maskinlæring i produkter og tjenester",
    domeneId: "data-integrasjon", verdistrøm: "Tverrgående",
    teamtype: "Støtteteam", prosesstype: "Kjerne", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 0, modenhetMål: 0, klassifisering: "IkkeVurdert",
    notater: "Koblet til KI-CoE i Teknologi-avdelingen",
    realisering: { verktøy: ["Azure OpenAI", "Azure ML", "Microsoft Copilot"] },
    gartnerKategori: { domene: "Data and analytics services", kategori: "AI cognitive services" },
  },
  {
    id: "k42", navn: "Privilegert tilgangsstyring (PAM)",
    beskrivelse: "Evnen til å styre, overvåke og beskytte privilegerte tilganger til kritiske systemer",
    domeneId: "sikkerhet-risiko", verdistrøm: "Tverrgående",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 0, modenhetMål: 0, klassifisering: "IkkeVurdert", notater: "",
    realisering: { verktøy: ["CyberArk", "Azure PIM"] },
    gartnerKategori: { domene: "Security, identity and access management", kategori: "Privilege access management testing" },
  },
  {
    id: "k43", navn: "Trusseldeteksjon og hendelsesrespons (SIEM/SOAR)",
    beskrivelse: "Evnen til å detektere, analysere og respondere på sikkerhetstrusler systematisk",
    domeneId: "sikkerhet-risiko", verdistrøm: "Tverrgående",
    teamtype: "Støtteteam", prosesstype: "Styring", eierskap: "Kjerne", kritikalitet: "Høy",
    modenhetNå: 0, modenhetMål: 0, klassifisering: "IkkeVurdert", notater: "",
    realisering: { verktøy: ["Microsoft Sentinel", "Microsoft Defender XDR"] },
    gartnerKategori: { domene: "Security, identity and access management", kategori: "Threat detection, investigation and response" },
  },
];
